### ISSUE TITLE
no-reference methods

### ISSUE THREAD

**Issue by gitunit** [slhck/ffmpeg-quality-metrics#37]
do you support any no-reference methods (NORM)? any idea if there is something in FFMPEG?

would be great
(greetings from your former study mate :stuck_out_tongue_closed_eyes:)

**Comment by slhck** [comment]
I can (or want to?) really only support what is included in FFmpeg, and there are no no-reference metrics implemented. 

The problem is that there is no NR metric available (at least to my knowledge) that:

1. Works well (in terms of accuracy)
1. Is not just an indicator for a single type of artifact (e.g., blurring, noise)
1. Has free, open-source code
1. Is somewhat cross-platform (*nix)

**Comment by slhck** [comment]
Closed for the time being. PRs are welcome to add NR metrics if ffmpeg supports them or they can be easily added.
