### ISSUE TITLE
vif_avg is missing

### ISSUE THREAD

**Issue by huiyiygy** [slhck/ffmpeg-quality-metrics#41]
In the new version 3.0.0, the metric VIF only return scores of scale_0, scale_1, scale_2, scale_3. 
Missing score vif_avg，while it was return in the old version. 
Is it possible to add it in the new version？

**Comment by slhck** [comment]
The `vif_avg` in v2.x was computed using the average of `scale_0`. I did this manually because the VIF metric did not output a general average per frame, and only the individual scales. The default scale, obviously, is 0, where no scaling is applied.

v3.x of this tool outputs the global averages for each submetric, and no longer makes assumptions about what the "standard" submetric should be. So, please use `global.vif.scale_0.average` to get the global average.
